### ISSUE TITLE
Multiples balises `<name>` dans `<language>

### ISSUE THREAD

**Issue by OrianeN** [DEFI-COLaF/metadata#12]
Est-ce qu'il serait possible d'accepter plusieurs balises `<name>` dans la balise `<language>` ? 

Je souhaiterais pouvoir indiquer le nom de la langue en français ainsi qu'en occitan dans le forum converti en TEI, par exemple:

```xml
<language ident="met-occ-lan">
     <idno type="langue">
      met-occ-lan
     </idno>
     <idno type="script">
      latin
     </idno>
     <name>
      Occitan - Languedocien
     </name>
     <name xml:lang="met-occ">
      Lengadocian
     </name>
     <date from="2007" to="2012"/>
     <location/>
    </language>
```

Pour l'instant j'ai une erreur sur le deuxième `<name>`:
> element "name" not allowed here; expected the element end-tag or element "date" or "location"

**Comment by Juliettejns** [comment]
Réalisé dans la branche prototype tei
