### ISSUE TITLE
Element `<list>` not allowed in `<p>`

### ISSUE THREAD

**Issue by OrianeN** [DEFI-COLaF/metadata#17]
I'm trying to detect and format lists from the posts in Forum Occitania (although the HTML doesn't contain explicit `<ul>`/`<ol>`/`<li>`). 
I found the element `<list>` in the TEI documentation (https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-list.html) but I get an error with your schema: 
> element "list" not allowed here; expected the element end-tag, text or element "dateline", "figure", "foreign", "fw", "hi", "lb", "pb", "ref", "s", "signed" or "w"

```xml
<p>
  <lb/>Donc fau d'engueras trobar, per nostres jogadors:
  <list rend="bulleted">
    <item>-l'atge de la Marilis Orionaa</item>
    <item>-l'atge de la Rosina de Peira</item>
    <item>-l'atge dau Papet J</item>
  </list>
</p>
```

Could you please add this element to the ones allowed in `<p>` ?

**Comment by OrianeN** [comment]
Thanks for your advice @Juliettejns, I should be able to do that !

**Comment by OrianeN** [comment]
C'est bon pour les listes en dehors des paragraphes, sauf quand c'est dans des `<quote>` où j'ai encore une erreur:
> element "list" not allowed here; expected the element end-tag, text or element "label", "lb", "lg", "p", "quote" or "ref"

```xml
<post when="2007-12-01T10:54" who="#P-024" xml:id="post-t00406-03027" xml:lang="met-occ-lim">
  <certainty assertedValue="met-occ" degree="1.0" locus="value" match="@xml:lang" source="#fasttext-lid218e-post"/>
  <quote corresp="#post-t00406-03024">
    <p>
      <lb/>Sei lo sol a jugar o qué ?
      <lb/>Bon, vau perpausar :
    </p>
    <list rend="bulleted">
      <item>-Jali a 52 ans</item>
      <item>-Marilis a 48 ans</item>
      <item>-Rosina a 70 ans</item>
      <item>-Patric a 62 ans</item>
      <item>-Sicre a 60 ans</item>
    </list>
    <p>
      <lb/>Veiqui.
    </p>
  </quote>
```

**Comment by Juliettejns** [comment]
C'est ajouté et push dans github:)
