### ISSUE TITLE
Enable element `<media>`

### ISSUE THREAD

**Issue by OrianeN** [DEFI-COLaF/metadata#19]
J'aimerais utiliser l'élément `<media>` (https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-media.html) pour encoder les vidéos/audios des posts du forum Occitania. Est-ce que tu pourrais ajouter cet élément au schéma COLaF stp ? (Il me semblait qu'il y était mais je vois des erreurs sur tous ces éléments depuis quelques jours...)

Par exemple:
```xml
<post when="2008-07-04T19:28" who="#P-048" xml:id="post-t00803-07285" xml:lang="met-occ-gas">
  <certainty assertedValue="met-occ" degree="1.0" locus="value" match="@xml:lang" source="#fasttext-lid218e-post"/>
  <p>
    <lb/>E coneishetz Castelhemis ?
    <lb/>L'èi descobèrt suu youtube, qu'ei un landés
  </p>
  <media mimeType="video" url="https://www.youtube.com/embed/TtbRsr3eW2Q" width="560"/>
  <p>
    <lb/>A la fin que canta en occitan  
    <figure type="emoji">
      <head>Plan Urós</head>
      <graphic url="https://2img.net/i/fa/i/smiles/icon_biggrin.png"/>
    </figure>
  </p>
</post>
```

**Comment by Juliettejns** [comment]
Bonjour Oriane, 
j'aurais aimé éviter d'avoir trop de balises spécifiques à un corpus unique dans COLaF.... Après c'est vrai que c'est la balise qui correspond exactement. Ce que je te propose c'est de la mettre pour le moment, avec un veto: si on se rend compte qu'il n'y a des media que dans ce forum, on le passera en figure.

**Comment by OrianeN** [comment]
Bonjour Juliette,

Je viens de tomber sur erreur à cause d'une balise `<media>` dans une `<quote>`, est-ce que tu pourrais rajouter ce cas stp ?

**Comment by Juliettejns** [comment]
Bonjour Oriane, c'est modifié! Merci pour ta vigilance:)

**Comment by OrianeN** [comment]
> Bonjour Oriane, c'est modifié! Merci pour ta vigilance:)

Merci à toi !
