### ISSUE TITLE
Date of writing vs. date of publication

### ISSUE THREAD

**Issue by rasuljasirdent** [DEFI-COLaF/metadata#25]
Do we have a tag to indicate when a work was originally written? In concrete terms, I have some novels that were published serially in the early 1800s, but the corpus sources are compilations published in the late 1800s. For the timeline that I am creating, the date of writing is somewhat more important than the date of publication, but I'm not sure what the best way to mark it is.

**Comment by Juliettejns** [comment]
Hi Rasul, 
I can propose you to have 2 different bibl, 1 for the novel, 1 for the corpus compilation such as:
```
<sourceDesc>
                                <bibl type="printSource">
                                    <title>Title of the novel</title>
                                    <author>Author of the novel</author>
                                    <date when="1892"/> (date of the novel)
                                </bibl>
                                <bibl type="corpusSource">
                                    <title>Title of the corpus</title>
                                    <author>Author of the corpus</author>
                                    <publisher ref="https://distant-reading.net">Publisher of the corpus</publisher>
                                     <pubplace>pubplace</pubplace>
                                    <date when="2021-04-09"/> date of the corpus
                                </bibl>
                            </sourceDesc>
```
Hope that will answer your question! Do not hesitate to show me how it looks on your document.

**Comment by rasuljasirdent** [comment]
Thanks!
I currently have it set up similarly:
![image](https://github.com/user-attachments/assets/35086548-220e-49b3-8892-72ca4cf733eb)

As you can see, the main issue is that I really want to include three dates. The publication date of the novel and the corpus publication are pretty straightforward, but I'm not finding any valid way to include when the book was written. For the moment, I have included it in parenthesis, but I know this is not valid XML.

**Comment by Juliettejns** [comment]
Can you send me where you've got the date informations? I can find them in google books. I want to look at it so I can get a crasp of the different dates you're talking out since I'm not sure I understand everything correctly?

**Comment by rasuljasirdent** [comment]
Sure. This is a somewhat complicated example, as it's a sequel. The [first book](https://www.google.fr/books/edition/L_amour_d_un_N%C3%A8gre/CKSWUG4ujhoC?hl=en&gbpv=1&dq=jobey+%22au+moment+o%C3%B9%22&pg=PA1&printsec=frontcover) was published in 1860 and it has an introductory autobiographical note explaining the author explaining how the author left Louisiana in 1840 but wrote the books using notes from when he was there (late 1830s). Various snippets from the books appear in print before the full publication though, like  [this song](https://www.google.fr/books/edition/Journal_pour_tous/PJtLAAAAcAAJ?hl=en&gbpv=1&dq=%22y%C3%A9%22+louisiane+%22li%22&pg=PA812&printsec=frontcover).

A similar thing happens with [this author](https://fr.wikisource.org/wiki/Une_de_perdue,_deux_de_trouv%C3%A9es/Tome_I), who lived in Louisiana from 1838 to 1843 and originally published his books  [in serial format in the late 1840s](https://www.google.fr/books/edition/Album_litt%C3%A9raire_et_musical_de_la_Revue/0RPnAAAAMAAJ?hl=en&gbpv=1&dq=%22f%C3%A9s%C3%A9%22+%22li%22&pg=RA1-PA224&printsec=frontcover) before publishing them as full novels in 1874.

The idea is that even though the books were published in the second half of the 19th century, we are interested in them because they describe the linguistic situation in the 1830s/40s.

**Comment by Juliettejns** [comment]
Oh ok I think I understood better what you meant! 
I think the best thing to do is using the date element in langUsage... Since 1836 is defining the date for the language.
Is it okay for you?
Could you give you send me the XML file you're working on so I can show you precisely what I mean?

**Comment by rasuljasirdent** [comment]
Of course! I sent it via Mattermost since I can't load XML in the thread.

**Comment by Juliettejns** [comment]
Likewise:)
