### ISSUE TITLE
Element `<figDesc>` not allowed

### ISSUE THREAD

**Issue by OrianeN** [DEFI-COLaF/metadata#31]
Bonjour Juliette,

En corrigeant des erreurs sur le TEI du Forum Occitania, j'ai voulu convertir les attributs HTML `alt` des images par l'élément TEI `<figDesc>` plutôt que par `<head>` car j'ai trouvé des cas où j'ai besoin des deux éléments, et je trouvais ça plus logique ainsi.

Un exemple de post en HTML où j'aimerais utiliser les deux balises: https://occitania.forumactif.com/t3-lo-clavier-en-oc#13069
```html
<fieldset>
  <legend><strong> « french legacy »</strong></legend>
  <a href="https://servimg.com/view/12563505/12" target="_blank" rel="nofollow"><img src="https://i.servimg.com/u/f86/12/56/35/05/french13.png" alt="Lo clavièr en òc French13" class="" style="display:inline"></a>
</fieldset>
```

Je te propose cette conversion:
```xml
<figure>
  <head rend="bold"> « french legacy »</head>
  <figDesc>Lo clavièr en òc French13</figDesc>
  <graphic url="https://i.servimg.com/u/f86/12/56/35/05/french13.png"/>
</figure>
```

Malheureusement, l'élément [`<figDesc>`](https://tei-c.org/release/doc/tei-p5-doc/fr/html/ref-figDesc.html) n'est pas dans le schéma TEI-COLaF. Est-ce que tu accepterais de l'ajouter ?

**Comment by Juliettejns** [comment]
Bonjour Oriane, 
Figdesc est bien compris dans la documentation (1.3.4.3. Images et tableaux), tu as même des exemples d'utilisations. N'hésite pas à la consulter.
J'ai cependant effectivement non push son ajout de figdesc au schéma sur le github, une erreur de ma part. C'est corrigé.

**Comment by OrianeN** [comment]
Merci !
